### fazer post no fórum

POST http://localhost:3000/api/forum
Content-Type: application/json

{
    "user": "Usuário Teste",
    "profilePic": "https://cdn.discordapp.com/attachments/621499803884584998/1168562289453051945/marco-wulfr-marco-wulfr-twinning-blade-final-marcowulfr-closeup-pattern.jpg?ex=65523770&is=653fc270&hm=b41b6169e0acfa8967264547d1a7e1d4de58bf5bdd23c28fbec3e9e9184a408d&",
    "group": "Mesa Teste",
    "postContent": "qualquer coisa aqui só pra ver se tá funcionando"
}

### pegar todos os posts do fórum

GET http://localhost:3000/api/forum

### pegar post único no fórum

GET http://localhost:3000/api/forum/653fc5f9083030de512d975e

### deleção de post do fórum

DELETE  http://localhost:3000/api/forum/654297d16143d83271ee4306

### edição de post do fórum

PUT http://localhost:3000/api/forum/654297d16143d83271ee4306
Content-Type: application/json

{
    "user": "Usuário Teste",
    "profilePic": "https://cdn.discordapp.com/attachments/621499803884584998/1168562289453051945/marco-wulfr-marco-wulfr-twinning-blade-final-marcowulfr-closeup-pattern.jpg?ex=65523770&is=653fc270&hm=b41b6169e0acfa8967264547d1a7e1d4de58bf5bdd23c28fbec3e9e9184a408d&",
    "date": "01-11-23 15:23",
    "postContent": "teste de edição, meu patrão"
}





### MESAS ###

### criar nova mesa

POST http://localhost:3000/api/group
Content-Type: application/json

{
    "name": "Mesa Teste",
    "users": ["Usuário Teste 1", "Usuário Teste 2"],
    "owner": "Usuário Teste 1"
}

### pega todas as mesas

GET http://localhost:3000/api/group

### pegar mesa única

GET http://localhost:3000/api/group/655240dbd853a3a3b8c71551

### deleção de mesa

DELETE  http://localhost:3000/api/group/65524100d853a3a3b8c71555

### edição de mesa

PUT http://localhost:3000/api/group/655240dbd853a3a3b8c71551
Content-Type: application/json

{
    "name": "Mesa Teste - Editada",
    "users": ["Usuário Teste 1", "Usuário Teste 2"],
    "owner": "Usuário Teste 1"
}





### GM NOTES ###

### novo post em gm notes

POST http://localhost:3000/api/gm
Content-Type: application/json

{
    "user": "Usuário Teste",
    "profilePic": "https://cdn.discordapp.com/attachments/621499803884584998/1168562289453051945/marco-wulfr-marco-wulfr-twinning-blade-final-marcowulfr-closeup-pattern.jpg?ex=65523770&is=653fc270&hm=b41b6169e0acfa8967264547d1a7e1d4de58bf5bdd23c28fbec3e9e9184a408d&",
    "group": "Mesa Teste 25",
    "postContent": "teste do model"
}

### pegar todos os posts em gm notes

GET http://localhost:3000/api/gm

### pegar post único em gm notes

GET http://localhost:3000/api/gm/65562efbbefac6572f5d65b0

### deleção de post em gm notes

DELETE  http://localhost:3000/api/gm/65562efbbefac6572f5d65b0

### edição de post em gm notes

PUT http://localhost:3000/api/gm/65562efbbefac6572f5d65b0
Content-Type: application/json

{
    "user": "Usuário Teste",
    "profilePic": "https://cdn.discordapp.com/attachments/621499803884584998/1168562289453051945/marco-wulfr-marco-wulfr-twinning-blade-final-marcowulfr-closeup-pattern.jpg?ex=65523770&is=653fc270&hm=b41b6169e0acfa8967264547d1a7e1d4de58bf5bdd23c28fbec3e9e9184a408d&",
    "group": "Qualquer porra aqui só pra ver se vai",
    "postContent": "teste de edição, meu patrão"
}






### FURTHER READING ###

### novo post em further reading

POST http://localhost:3000/api/reading
Content-Type: application/json

{
    "user": "Usuário Teste",
    "profilePic": "https://cdn.discordapp.com/attachments/621499803884584998/1168562289453051945/marco-wulfr-marco-wulfr-twinning-blade-final-marcowulfr-closeup-pattern.jpg?ex=65523770&is=653fc270&hm=b41b6169e0acfa8967264547d1a7e1d4de58bf5bdd23c28fbec3e9e9184a408d&",
    "group": "Mesa Teste",
    "postContent": "mais um teste do further reading só pra garantir"
}

### pegar todos os posts em further reading

GET http://localhost:3000/api/reading

### pegar post único em further reading

GET http://localhost:3000/api/reading/655b676d71258a3d322238f3

### deleção de post em further reading

DELETE  http://localhost:3000/api/reading/655b676d71258a3d322238f3

### edição de post em further reading

PUT http://localhost:3000/api/reading/655b675b71258a3d322238f1
Content-Type: application/json

{
    "user": "Usuário Teste",
    "profilePic": "https://cdn.discordapp.com/attachments/621499803884584998/1168562289453051945/marco-wulfr-marco-wulfr-twinning-blade-final-marcowulfr-closeup-pattern.jpg?ex=65523770&is=653fc270&hm=b41b6169e0acfa8967264547d1a7e1d4de58bf5bdd23c28fbec3e9e9184a408d&",
    "group": "Qualquer porra aqui só pra ver se vai",
    "postContent": "teste de edição no further reading, meu patrão"
}



### USERS ###

### Criando user

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Usuário Teste 3",
    "email": "teste4@teste4",
    "password": "SenhaTeste",
    "confirmPassword": "SenhaTeste"
}

### pegar todos os users

GET http://localhost:3000/auth/register

### Criando user

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "teste4@teste4",
    "password": "SenhaTeste"
}